apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ .Values.name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        app.kubernetes.io/name: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image }}
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: {{ .Values.service.port }}
            protocol: TCP
        envFrom:
          - configMapRef:
              name: {{ .Values.name }}
        livenessProbe:
          httpGet:
            path: {{ .Values.probe.path }}
            port: {{ .Values.service.port }}
          initialDelaySeconds: {{ .Values.probe.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.probe.livenessProbe.periodSeconds }}
        startupProbe:
          httpGet:
            path: {{ .Values.probe.path }}
            port: {{ .Values.service.port }}
          initialDelaySeconds: {{ .Values.probe.startupProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.probe.startupProbe.periodSeconds }}
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
