name: app-agsr
replicaCount: 3
image: "lostroma/test-task-agsr:latest"
service:
  port: 80
namespace: app-agsr
probe:
  path: /health
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
  startupProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
resources:
  requests:
    memory: "128Mi"
    cpu: "50m"
  limits:
    memory: "512Mi"
    cpu: "500m"
environments:
  app_message: "Test service for AGSR"
